import type { SectorValue } from '@domain/lead/value-objects/sector.vo';

export const SECTOR_ICONS: Record<SectorValue, string> = {
  'Clínicas & Consultórios': '🏥',
  'Clínicas de Estética': '💆',
  'Clínicas Veterinárias & Pet': '🐾',
  'Psicólogos & Terapeutas': '🧠',
  'Fisioterapia & Pilates': '🧘',
  Odontologia: '🦷',
  'Salões & Barbearias': '✂️',
  'Salões Femininos': '💇',
  'Nail Designers': '💅',
  'Estúdios de Tatuagem': '🎨',
  Restaurantes: '🍽️',
  'Lanchonetes & Hamburguerias': '🍔',
  'Padarias & Confeitarias': '🥐',
  'Marmitarias & Delivery': '🍱',
  'Oficinas Mecânicas': '🔧',
  'Academias & Estúdios': '💪',
  'Fotógrafos & Estúdios': '📸',
  'Serviços Domésticos': '🧹',
  Advocacia: '⚖️',
  Contabilidade: '📊',
  'Escolas & Cursos': '🎓',
  'Igrejas & Ministérios': '⛪',
};
